# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mtgrecorder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.PositiveIntegerField(default=0)),
                ('loss', models.PositiveIntegerField(default=0)),
                ('ties', models.PositiveIntegerField(default=0)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester', to='mtgrecorder.Player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmer', to='mtgrecorder.Player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtgrecorder.Tournament')),
            ],
        ),
        migrations.RemoveField(
            model_name='match',
            name='verified',
        ),
        migrations.AlterField(
            model_name='match',
            name='date_submitted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
