# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtgrecorder', '0002_auto_20160505_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorerequest',
            name='verified',
            field=models.IntegerField(choices=[(b'1', b'Unverified'), (b'2', b'Confirm'), (b'3', b'Decline')], default=1),
        ),
    ]
