# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mtgrecorder', '0003_auto_20160506_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='participants',
            field=models.ManyToManyField(to='mtgrecorder.Player'),
        ),
        migrations.AlterField(
            model_name='scorerequest',
            name='verified',
            field=models.IntegerField(choices=[(1, b'Unverified'), (2, b'Confirm'), (3, b'Decline')], default=1),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to='mtgrecorder.Player'),
        ),
    ]
